### ISSUE TITLE
Update Positron style json to decrease visual weight of park areas

### ISSUE THREAD

**Issue by makella** [CartoDB/basemap-styles#16]
@skgsergio what we discussed friday! will have a PR ready today.

thanks!

**Comment by makella** [comment]
PR with details:
https://github.com/CartoDB/basemap-styles/pull/17

**Comment by skgsergio** [comment]
I made several changes:

- Merged #17
- Improvements PR merged #18 (this doesn't affect at all to the styles)
  - Made several improvements to the script that generates the style using the template and the variables files. This was not needed 100% but now performs a sanity check so there are no missing variables. This doesn't affect the result file (tested with the other styles that weren't modified).
  - Added a couple of variables to address a couple of issues: basemap name (#10) and wrong URL for sprites. All styles use the same sprites so this was not an issue but is better to have it fixed instead all using Dark Matter sprites URL.

![image](https://user-images.githubusercontent.com/186349/59261179-4466eb00-8c3d-11e9-9e7e-a25a470f7ee0.png)

**Comment by makella** [comment]
nice work!! thank you so much!!

**Comment by skgsergio** [comment]
Deployed to prod! 🚀
