### ISSUE TITLE
Positron Vector (mapbox-gl) is too green

### ISSUE THREAD

**Issue by jaakla** [CartoDB/basemap-styles#4]
Greens (parks) are too vivid in Positron mapbox-gl version. See here:

https://cartodb.github.io/basemap-styles/#zoom%3D11%3Blat%3D47.93%3Blon%3D1.98%3Br1%3Dleaflet%3Br2%3Dgl%3Br3%3Dleaflet%3Br4%3Dleaflet%3Bs1%3DPositron%20raster%20(Retina)%3Bs2%3DPositron%20Vector%20on%20Mapbox-GL%3Bs3%3DVoyager%20raster%3Bs4%3DVoyager%20raster%20(Retina)

Maybe colour is from Voyager?

@makella

**Comment by skgsergio** [comment]
Solved in #16
