### ISSUE TITLE
Recent rendering changes

### ISSUE THREAD

**Issue by davidmanzanares** [CartoDB/basemap-styles#8]
One of our E2E tests has shown one change half an hour ago. The difference is minor and the test seems to be non-deterministic since after re-running it, it showed the original reference image.

We would like to know if there have been changes recently in the basemaps (style or data), to know if the reason of this non-determinism is on CARTO VL / Mapbox GL side.
![reference](https://user-images.githubusercontent.com/1692175/42893401-80be6ae6-8ab4-11e8-8e75-786f66bca090.png)
![reference_out](https://user-images.githubusercontent.com/1692175/42893403-80de6c74-8ab4-11e8-80af-c44e0dda4451.png)

**Comment by skgsergio** [comment]
Not sure why this happened on that date but I guess this is not happening anymore. Also, the basemap service has been changed recently so this shouldn't happen again.
